theme: minima
minima:
  skin: dark
  author:
    name: Bruno Brasolin
    email: "brunobrasolinc@gmail.com"
  social_links:
    - { platform: github,  user_url: "https://github.com/BrunoBrasolin" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/bruno-brasolin/" }
